apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: learn-resource
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      max:
        cpu: "1"
        memory: "1Gi"
      type: Container
