apiVersion: codearts.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: codearts
spec:
  huaweiPlatformConfig:
    releaseServerBaseUrl: https://cloudrelease-ext.ap-southeast-3.myhuaweicloud.com
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: codearts-secret
      key: credentials
